### PR TITLE
fix: remove old value when type changes

### LINKED ISSUE #114: Issue with changing value type of e.g. set pointer
Creating a set pointer node and trying to change the type of the value field results in the following error:

Image

Image

The issue seems to come from here:
https://github.com/KhronosGroup/glTF-InteractivityGraph-AuthoringTool/blob/17cb4d7c57754078fa582414a6b0519d830e8b17/src/authoring/AuthoringGraphNode.tsx#L77

I assume the `socketId` should be parsed from the dropdown options, but this does not seem to work anymore.

### PR DESCRIPTION
**Pull request by mattmacf98**
# Description
fixes https://github.com/KhronosGroup/glTF-InteractivityGraph-AuthoringTool/issues/114
there were two issues

1. there was an erroneous prefix `$` before `typeDropDown-${socket}`
2. the pointer set value remained after the type was changed (so going from bool -> int still retained the bool like value)

# Testing 
ran locally and did not get errors and confirmed old type value got wiped

https://github.com/user-attachments/assets/4ef991a6-13e2-4c5f-b727-bca62e2e7e57

### CODE REVIEW

File: src/authoring/AuthoringGraphNode.tsx [hunk 1]
```diff
@@ -522,17 +523,18 @@ export const AuthoringGraphNode = (props: IAuthoringGraphNodeProps) => {
                                 return (
                                     <div key={socket} className={"flow-node-socket"}>
                                         <label htmlFor={socket}>{socket}</label>
-                                        <input id={`in-${socket}`} name={socket} onChange={onChangeParameter} defaultValue={inputValues[socket].value} style={{display: props.data.linked && props.data.linked[socket] ? "none" : "block"}}/>
-                                        <select id={`$typeDropDown-${socket}`} onChange={onChangeType} defaultValue={inputValues[socket].type} style={{display: props.data.linked && props.data.linked[socket] ? "none" : "block"}}>
+                                        <input id={`in-${socket}`} name={socket} onChange={onChangeParameter} defaultValue={inputValues[socket].value} style={{ display: props.data.linked && props.data.linked[socket] ? "none" : "block" }} />
+                                        <select id={`typeDropDown-${socket}`} onChange={onChangeType} defaultValue={inputValues[socket].type} style={{ display: props.data.linked && props.data.linked[socket] ? "none" : "block" }}>
```
Comment (mattmacf98) [inline src/authoring/AuthoringGraphNode.tsx:527]: change to remove bad prefix `$`

File: src/authoring/AuthoringGraphNode.tsx [hunk 2]
```diff
@@ -70,20 +70,21 @@ export const AuthoringGraphNode = (props: IAuthoringGraphNodeProps) => {
...
         const curParam = inputValues[socketId];
-        setInputValues({...inputValues, [socketId]: {value: castParameter(evt.target.value, standardTypes[curParam.type!]!.name!), typeOptions:curParam.typeOptions, type:curParam.type}});
+        setInputValues({ ...inputValues, [socketId]: { value: castParameter(evt.target.value, standardTypes[curParam.type!]!.name!), typeOptions: curParam.typeOptions, type: curParam.type } });
     }, [inputValues]);
 
     const onChangeType = useCallback((evt: { target: { value: any; }; }) => {
         const socketId = (evt.target as HTMLInputElement).id.replace("typeDropDown-", "");
         const curParam = inputValues[socketId];
-        setInputValues({...inputValues, [socketId]: {value: curParam.value, typeOptions:curParam.typeOptions, type:evt.target.value}});
+        const newParam: IInteractivityValue = { value: [undefined], typeOptions: curParam.typeOptions, type: evt.target.value }
```
Comment (mattmacf98) [inline src/authoring/AuthoringGraphNode.tsx:79]: better setting of new param to wipe old value
